title: Wei Guo
position: Ph.D. Student
affiliation: George Washington University
email: weiguo (at) gwu.edu
keywords: weiguo
google_scholar: https://scholar.google.com/citations?user=KfJQzHQAAAAJ&hl=en
github_link: https://github.com/weiguowilliam
linkedin: https://www.linkedin.com/in/weiguowilliam/
avatar: ./assets/img/2008.png
google_analytics: UA-111540567-4
favicon: ./assets/img/tiger.png
favicon_dark: ./assets/img/tiger.png
description: The academic personal website of Wei Guo.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light