title: Wei Guo
position: Ph.D.
affiliation: Amazon
email: weiguo (at) gwu.edu
keywords: weiguo
google_scholar: https://scholar.google.com/citations?user=zAA-h7MAAAAJ&hl=en
cv_link: ./assets/CV.pdf
linkedin: https://www.linkedin.com/in/weiguowilliam/
avatar: ./assets/img/wei2.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/tiger.png
favicon_dark: ./assets/img/tiger.png
description: The academic personal website of Wei Guo.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
